#!/bin/bash

# Given some html (on stdin), wraps it in html that applies the same aesthetic
# that github uses for rendering markdown-processed content

# Usage:
# markdown < in.md | ghstyles > out.html

# If you have node.js installed I recommend the [marked] processor. It's fast,
# supports "github flavored" markdown by default and has no dependencies
# (other than node itself).

# [marked]:https://github.com/chjj/marked

# If stdin is terminal then bail
[[ -t 0 ]] && {
  echo 'pipe something to me!'
  exit 1
}

# no `readlink -f` on OSX, hax hax, grumble grumble
# https://github.com/harto/realpath-osx
realpath="$(python -c 'import os,sys; print os.path.realpath(sys.argv[1])' "$0")"
PATH="$(dirname "$realpath"):$PATH"

host="http://assets-cdn.github.com"
path="/assets/github-$(github-css-id).css"

cat <<HTML # Concatenate header
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<!-- Use Github's CDN for assets -->
<base href="$host">
<!-- Github stylesheet that includes styles for markdown formatted content -->
<link href="$path" rel="stylesheet" type="text/css">
<!-- Style article chrome -->
<style>
  article {
    margin: 64px auto;
    box-sizing: border-box;
    width: 910px;
    padding: 30px;
    border: 1px solid #ddd;
    border-radius: 2px;
    box-shadow: 0px 0px 2px #ddd;
  }
</style>
</head>
<body>
<article class="markdown-body">
HTML

cat # Concatenate stdin

cat <<HTML # Concatenate footer
</article>
</body>
</html>
HTML
